#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanTimeDirectories
cleanAuxiliary 2>/dev/null
cleanPostProcessing

cleanFaMesh

rm -rf processor*

#------------------------------------------------------------------------------
