#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

#------------------------------------------------------------------------------

wclean meshLibrary
wclean -all executables
wclean -all utilities

#------------------------------------------------------------------------------
